import { KeyedObject } from '../../Types';

export const scopes = [
  'channel:moderate',
  'chat:read',
  'chat:edit',
  'whispers:read',
  'whispers:edit',
  'analytics:read:extensions',
  'analytics:read:games',
  'bits:read',
  'channel:edit:commercial',
  'channel:manage:broadcast',
  'channel:read:charity',
  'channel:manage:extensions',
  'channel:manage:moderators',
  'channel:manage:polls',
  'channel:manage:predictions',
  'channel:manage:raids',
  'channel:manage:redemptions',
  'channel:manage:schedule',
  'channel:manage:videos',
  'channel:read:editors',
  'channel:read:goals',
  'channel:read:hype_train',
  'channel:read:polls',
  'channel:read:predictions',
  'channel:read:redemptions',
  'channel:read:stream_key',
  'channel:read:subscriptions',
  'channel:read:vips',
  'channel:manage:vips',
  'clips:edit',
  'moderation:read',
  'moderator:manage:announcements',
  'moderator:manage:automod',
  'moderator:read:automod_settings',
  'moderator:manage:automod_settings',
  'moderator:manage:banned_users',
  'moderator:read:blocked_terms',
  'moderator:manage:chat_messages',
  'moderator:read:chat_settings',
  'moderator:manage:chat_settings',
  'moderator:read:chatters',
  'moderator:read:shield_mode',
  'moderator:manage:shield_mode',
  'moderator:read:shoutouts',
  'moderator:manage:shoutouts',
  'moderator:read:followers',
  'moderator:read:suspicious_users',
  'user:edit',
  'user:edit:follows',
  'user:manage:blocked_users',
  'user:read:blocked_users',
  'user:read:broadcast',
  'user:manage:chat_color',
  'user:read:email',
  'user:read:follows',
  'user:read:subscriptions',
  'user:manage:whispers',
];

export const eventsubs = {
  'automod.message.hold': 'Automod Message Hold',
  'automod.message.update': 'Automod Message Update',
  'automod.settings.update': 'Automod Settings Update',
  'automod.terms.update': 'Automod Terms Update',
  'channel.update': 'Channel Update',
  'channel.follow': 'Follow',
  'channel.subscribe': 'Subscribe',
  'channel.subscription.end': 'Subscription End',
  'channel.subscription.gift': 'Subscription Gift',
  'channel.subscription.message': 'Subscription Message',
  'channel.cheer': 'Cheer',
  'channel.raid': 'Raid',
  'channel.ban': 'Ban',
  'channel.unban': 'Unban',
  'channel.moderate': 'Mod Action',
  'channel.moderator.add': 'Mod Add',
  'channel.moderator.remove': 'Mod Remove',
  'channel.unban_request.create': 'Unban Request Create',
  'channel.unban_request.resolve': 'Unban Request Resolve',
  'channel.vip.add': 'VIP Add',
  'channel.vip.remove': 'VIP Remove',
  'channel.channel_points_custom_reward.add': 'Channel Points Custom Reward Add',
  'channel.channel_points_custom_reward.update': 'Channel Points Custom Reward Update',
  'channel.channel_points_custom_reward.remove': 'Channel Points Custom Reward Remove',
  'channel.channel_points_custom_reward_redemption.add':
    'Channel Points Custom Reward Redemption Add',
  'channel.channel_points_custom_reward_redemption.update':
    'Channel Points Custom Reward Redemption Update',
  'channel.guest_star_session.begin': 'Guest Star Start',
  'channel.guest_star_session.end': 'Guest Star End',
  'channel.guest_star_guest.update': 'Guest Star Update',
  'channel.guest_star_settings.update': 'Guest Star Settings Update',
  'channel.poll.begin': 'Poll Begin',
  'channel.poll.progress': 'Poll Progress',
  'channel.poll.end': 'Poll End',
  'channel.prediction.begin': 'Prediction Begin',
  'channel.prediction.progress': 'Prediction Progress',
  'channel.prediction.lock': 'Prediction Lock',
  'channel.prediction.end': 'Prediction End',
  'channel.charity_campaign.donate': 'Charity Donate',
  'channel.charity_campaign.start': 'Charity Start',
  'channel.charity_campaign.progress': 'Charity Progress',
  'channel.charity_campaign.stop': 'Charity Stop',
  'drop.entitlement.grant': 'Drop Entitlement Grant',
  'extension.bits_transaction.create': 'Extension Bits Transaction Create',
  'channel.goal.begin': 'Goal Begin',
  'channel.goal.progress': 'Goal Progress',
  'channel.goal.end': 'Goal End',
  'channel.hype_train.begin': 'Hype Train Begin',
  'channel.hype_train.progress': 'Hype Train Progress',
  'channel.hype_train.end': 'Hype Train End',
  'channel.shield_mode.begin': 'Shield Mode Begin',
  'channel.shield_mode.end': 'Shield Mode End',
  'channel.shoutout.create': 'Shoutout Create',
  'channel.shoutout.receive': 'Shoutout Receive',
  'stream.online': 'Stream Online',
  'stream.offline': 'Stream Offline',
  'user.authorization.grant': 'User Authorization Grant',
  'user.authorization.revoke': 'User Authorization Revoke',
  'user.update': 'User Update',
} as KeyedObject;
